# Generated by Django 5.0 on 2025-08-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
