# Generated by Django 5.0 on 2025-08-05 09:25

import admin_dashboard.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0002_staffmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=admin_dashboard.storage_backends.MediaStorage(), upload_to='staff/cv'),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='image',
            field=models.FileField(blank=True, null=True, storage=admin_dashboard.storage_backends.MediaStorage(), upload_to='images/staff_images'),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
