# Generated by Django 5.0 on 2025-01-30 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_expensemodel_date_alter_feepaymentmodel_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feemastermodel',
            name='unique_fee_master_type_combo',
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 1, 30)),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2025, 1, 30)),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'CASH'), ('pos', 'POS'), ('bank', 'BANK TELLER'), ('transfer', 'BANK TRANSFER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feepaymentsummarymodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2025, 1, 30)),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 1, 30)),
        ),
    ]
