# Generated by Django 5.0 on 2025-02-21 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_feemastermodel_unique_fee_master_type_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feemastermodel',
            name='is_new',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 2, 21)),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2025, 2, 21)),
        ),
        migrations.AlterField(
            model_name='feepaymentsummarymodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2025, 2, 21)),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 2, 21)),
        ),
    ]
