# Generated by Django 5.0 on 2025-04-14 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_feemastermodel_is_new_alter_expensemodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 4, 14)),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2025, 4, 14)),
        ),
        migrations.AlterField(
            model_name='feepaymentsummarymodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2025, 4, 14)),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 4, 14)),
        ),
    ]
