# Generated by Django 5.0 on 2025-08-04 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_expensemodel_date_alter_feepaymentmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 8, 4)),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 4)),
        ),
        migrations.AlterField(
            model_name='feepaymentsummarymodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 4)),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 8, 4)),
        ),
    ]
