# Generated by Django 5.0 on 2025-08-05 09:25

import admin_dashboard.storage_backends
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_expensemodel_date_alter_feepaymentmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 8, 5)),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='expense_proof',
            field=models.FileField(blank=True, null=True, storage=admin_dashboard.storage_backends.MediaStorage(), upload_to='finance/expense'),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 5)),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, storage=admin_dashboard.storage_backends.MediaStorage(), upload_to='finance/fee_payment'),
        ),
        migrations.AlterField(
            model_name='feepaymentsummarymodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 5)),
        ),
        migrations.AlterField(
            model_name='feepaymentsummarymodel',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, storage=admin_dashboard.storage_backends.MediaStorage(), upload_to='finance/fee_payment'),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 8, 5)),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='income_proof',
            field=models.FileField(blank=True, null=True, storage=admin_dashboard.storage_backends.MediaStorage(), upload_to='finance/income'),
        ),
    ]
