# Generated by Django 5.0 on 2025-08-05 09:25

import admin_dashboard.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolgeneralinfomodel',
            name='logo',
            field=models.FileField(blank=True, storage=admin_dashboard.storage_backends.MediaStorage(), upload_to='images/logo'),
        ),
    ]
