# Generated by Django 5.0 on 2025-01-19 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('human_resource', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='assistant_class_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_class_rep', to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='assistant_form_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_form_teacher', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='class_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_rep', to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='form_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.classesmodel'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_section_info_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsectionmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_section_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsectionmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='academic.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='section',
            field=models.ManyToManyField(blank=True, to='academic.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='classsectionsubjectteachermodel',
            name='class_section',
            field=models.ManyToManyField(blank=True, to='academic.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='classsectionsubjectteachermodel',
            name='student_class',
            field=models.ManyToManyField(blank=True, to='academic.classesmodel'),
        ),
        migrations.AddField(
            model_name='classsectionsubjectteachermodel',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='classsectionsubjectteachermodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_section_subject_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsectionsubjectteachermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicsettingmodel',
            name='active_days',
            field=models.ManyToManyField(blank=True, related_name='active_days', to='academic.daysmodel'),
        ),
        migrations.AddField(
            model_name='academicsettingmodel',
            name='week_start_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.daysmodel'),
        ),
        migrations.AddField(
            model_name='lessondocumentmodel',
            name='student_class',
            field=models.ManyToManyField(blank=True, to='academic.classsectioninfomodel'),
        ),
        migrations.AddField(
            model_name='lessondocumentmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_document_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessondocumentmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonnotemodel',
            name='student_class',
            field=models.ManyToManyField(blank=True, to='academic.classsectioninfomodel'),
        ),
        migrations.AddField(
            model_name='lessonnotemodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_note_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonnotemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectgroupmodel',
            name='student_class',
            field=models.ManyToManyField(blank=True, to='academic.classesmodel'),
        ),
        migrations.AddField(
            model_name='subjectgroupmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_group_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectgroupmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectsmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectsmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectgroupmodel',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='subject_group', to='academic.subjectsmodel'),
        ),
        migrations.AddField(
            model_name='lessonnotemodel',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.subjectsmodel'),
        ),
        migrations.AddField(
            model_name='lessondocumentmodel',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.subjectsmodel'),
        ),
        migrations.AddField(
            model_name='classsectionsubjectteachermodel',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_class_section_info', to='academic.subjectsmodel'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='subject_class_info', to='academic.subjectsmodel'),
        ),
        migrations.AddConstraint(
            model_name='classsectionmodel',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_class_name_type_combo'),
        ),
        migrations.AddConstraint(
            model_name='classesmodel',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_name_class_type_combo'),
        ),
        migrations.AddConstraint(
            model_name='subjectsmodel',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_subject_name_type_combo'),
        ),
        migrations.AddConstraint(
            model_name='subjectgroupmodel',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_subject_group_combo'),
        ),
        migrations.AddConstraint(
            model_name='classsectioninfomodel',
            constraint=models.UniqueConstraint(fields=('student_class', 'section', 'type'), name='unique_student_class_section_combo'),
        ),
    ]
