# Generated by Django 5.0 on 2025-01-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classesmodel',
            name='is_nursery_class',
        ),
    ]
