# Generated by Django 5.0 on 2025-01-22 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_classesmodel_is_nursery_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classesmodel',
            name='is_graduation_class',
        ),
        migrations.RemoveField(
            model_name='classesmodel',
            name='promotion_class',
        ),
        migrations.CreateModel(
            name='PromotionClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_graduation_class', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.classsectionmodel')),
                ('promotion_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_class', to='academic.classesmodel')),
                ('promotion_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_section', to='academic.classsectionmodel')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.classesmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='promotionclassmodel',
            constraint=models.UniqueConstraint(fields=('student_class', 'class_section', 'type'), name='unique_promotion_class_combo'),
        ),
    ]
