# Generated by Django 5.0 on 2025-08-05 09:25

import admin_dashboard.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_headteachermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondocumentmodel',
            name='document',
            field=models.FileField(storage=admin_dashboard.storage_backends.MediaStorage(), upload_to='lesson_document'),
        ),
        migrations.AlterField(
            model_name='lessonnotemodel',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=admin_dashboard.storage_backends.MediaStorage(), upload_to='lesson_note'),
        ),
    ]
