# Generated by Django 5.0 on 2025-02-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmodel',
            name='is_new',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
