# Generated by Django 5.0 on 2025-08-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentsmodel_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmodel',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
