# Generated by Django 5.0 on 2025-08-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentsmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
