# Generated by Django 5.0 on 2025-08-05 09:25

import admin_dashboard.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentsmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsmodel',
            name='image',
            field=models.FileField(blank=True, null=True, storage=admin_dashboard.storage_backends.MediaStorage(), upload_to='images/parent_images'),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='image',
            field=models.FileField(blank=True, null=True, storage=admin_dashboard.storage_backends.MediaStorage(), upload_to='images/student_images'),
        ),
    ]
