# Generated by Django 5.0 on 2025-01-19 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st term', '1st Term'), ('2nd term', '2ndTerm'), ('3rd term', '3rd Term')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('attendant', models.CharField(blank=True, choices=[('student', 'STUDENT'), ('parent', 'PARENT'), ('staff', 'STAFF'), ('all', 'ALL')], max_length=10, null=True)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st term', '1st Term'), ('2nd term', '2ndTerm'), ('3rd term', '3rd Term')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st term', '1st Term'), ('2nd term', '2ndTerm'), ('3rd term', '3rd Term')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffClassAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st term', '1st Term'), ('2nd term', '2ndTerm'), ('3rd term', '3rd Term')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st term', '1st Term'), ('2nd term', '2ndTerm'), ('3rd term', '3rd Term')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClassAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st term', '1st Term'), ('2nd term', '2ndTerm'), ('3rd term', '3rd Term')], max_length=20)),
                ('attendance', models.JSONField(blank=True, null=True)),
                ('total_attendance', models.IntegerField(default=0)),
                ('present_attendance', models.IntegerField(default=0)),
                ('late_attendance', models.IntegerField(default=0)),
                ('absent_attendance', models.IntegerField(default=0)),
                ('last_attendance_date', models.DateField(blank=True, null=True)),
                ('last_present_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClassAttendanceRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st term', '1st Term'), ('2nd term', '2ndTerm'), ('3rd term', '3rd Term')], max_length=20)),
                ('date', models.DateField()),
                ('total_attendance', models.IntegerField(default=0)),
                ('present_attendance', models.IntegerField(default=0)),
                ('late_attendance', models.IntegerField(default=0)),
                ('absent_attendance', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st term', '1st Term'), ('2nd term', '2ndTerm'), ('3rd term', '3rd Term')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st term', '1st Term'), ('2nd term', '2ndTerm'), ('3rd term', '3rd Term')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_barcode_attendance', models.BooleanField(default=True)),
                ('use_id_attendance', models.BooleanField(default=False)),
                ('use_name_attendance', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
